### PR TITLE
add src to AssetPath

### PR DESCRIPTION
**Pull request by brookeangel**
This PR adds `src` to AssetPath. It allows a quick way to turn an AssetPath into the Html.Attribute src!

### CODE REVIEW

File: src/AssetPath.elm [hunk 1]
```diff
@@ -1,18 +1,21 @@
...
 
 {-| The core API of `AssetPath`: a union type and a function.
 
-@docs Asset, url
+@docs Asset, url, src
+
 -}
 
-import String
+import Html.Attributes
```
Comment (ento) [inline src/AssetPath.elm]: Build error says:

```
Cannot find type `Html.Attribute`.
55| src : Asset -> Html.Attribute msg
                   ^^^^^^^^^^^^^^
No module called `Html` has been imported. 
```
https://travis-ci.org/NoRedInk/elm-asset-path/builds/255841000

I think we want `import Html` in addition here. http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html#Attribute

File: src/AssetPath.elm [hunk 2]
```diff
@@ -46,6 +50,13 @@ url asset =
             toAbsoluteUrl path
 
 
+{-| Makes an Html src attribute from an asset.
```
Comment (ento) [inline src/AssetPath.elm]: 😻

**Comment by avh4** [comment]
@ento comments addressed!   (CI fails because of https://github.com/NoRedInk/elm-asset-path/pull/6 )
